services:
  foloup:
    build: .
    ports:
      - "4000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - weam_app-network
networks:
  weam_app-network:
    external: true
